# NUMPY(NUMERICAL PYTHON):
#### NumPy is a Python library.
#### NumPy is used for working with arrays.
#### NumPy is short for "Numerical Python".


## Import NumPy
#### Once NumPy is installed, import it in your applications by adding the import keyword:
##### import numpy as np

## Example
#### import numpy as np
#### arr = np.array([1, 2, 3, 4, 5])
#### print(arr)
##### output:[1 2 3 4 5]

## Creating Array
#### Use a tuple to create a NumPy array:


In [1]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print("mean:",np.mean(arr))
print("min:",np.min(arr))
print("max:",np.max(arr))
print("sum:",np.sum(arr))

[1 2 3 4 5]
mean: 3.0
min: 1
max: 5
sum: 15


#### Create a 0-D array with value 42

In [2]:
import numpy as np
arr = np.array(42)
print(arr)

42


#### Create a 1-D array containing the values 1,2,3,4,5:

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


#### Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

In [4]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


#### Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:



In [5]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### Check how many dimensions the arrays have:

In [6]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#### Create an array with 5 dimensions and verify that it has 5 dimensions:



In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Access Array Elements

##### Array indexing is the same as accessing an array element.
##### You can access an array element by referring to its index number.
##### The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.



#### Get the first element from the following array:

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


#### Get the second element from the following array.



In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[1])


2


#### Get third and fourth elements from the following array and add them.

In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


## Access 2-D Arrays
##### To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
##### Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

#### Access the element on the first row, second column:

In [11]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


#### Access the element on the 2nd row, 5th column:



In [12]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])


5th element on 2nd row:  10


## Access 3-D Arrays
##### To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

#### Access the third element of the second array of the first array:



In [2]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


#### Print the last element from the 2nd dim:

In [14]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## NumPy Array Slicing


##### Slicing in python means taking elements from one given index to another given index.
##### pass slice instead of index like this: [start:end].
##### We can also define the step, like this: [start:end:step].
##### If we don't pass start its considered 0
##### we don't pass end its considered length of array in that dimension
##### If we don't pass step its considered 1



#### Slice elements from index 1 to index 5 from the following array:



In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])


[2 3 4 5]


#### Slice elements from index 4 to the end of the array:

In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])


[5 6 7]


#### Slice elements from the beginning to index 4 (not included):

In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


## Negative Slicing
##### Use the minus operator to refer to an index from the end:



#### Slice from the index 3 from the end to index 1 from the end:

In [18]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


### STEP
##### Use the step value to determine the step of the slicing:
#### Return every other element from index 1 to index 5:



In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


#### Return every other element from the entire array:

In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])


[1 3 5 7]


## Slicing 2-D Arrays

#### From the second element, slice elements from index 1 to index 4 (not included):

In [21]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])


[7 8 9]


#### From both elements, return index 2:

In [22]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


#### From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [24]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## Shape of an Array
##### The shape of an array is the number of elements in each dimension.

#### Print the shape of a 2-D array:


In [25]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


#### Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

In [26]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


## NumPy Array Reshaping
##### Reshaping means changing the shape of an array.
##### The shape of an array is the number of elements in each dimension.
##### By reshaping we can add or remove dimensions or change number of elements in each dimension.
### Reshape From 1-D to 2-D
#### Convert the following 1-D array with 12 elements into a 2-D array.
#### The outermost dimension will have 4 arrays, each with 3 elements:

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Reshape From 1-D to 3-D
#### Convert the following 1-D array with 12 elements into a 3-D array.
#### The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:



In [28]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)  
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Returns Copy or View?
#### Check if the returned array is a copy or a view:

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)


[1 2 3 4 5 6 7 8]


### Unknown Dimension
##### You are allowed to have one "unknown" dimension.
##### Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
##### Pass -1 as the value, and NumPy will calculate this number for you.
#### Convert 1D array with 8 elements to 3D array with 2x2 elements:

In [30]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening the arrays
##### Flattening array means converting a multidimensional array into a 1D array.
##### We can use reshape(-1) to do this.
#### Convert the array into a 1D array:

In [31]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


## Random Numbers in NumPy
##### Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

#### Generate a random integer from 0 to 100:

In [4]:
from numpy import random
x = random.randint(50)
print(x)

21


#### The random module's rand() method returns a random float between 0 and 1.
#### Generate a random float from 0 to 1:

In [33]:
from numpy import random
x = random.rand()
print(x)

0.3162423909490206


#### Generate a 1-D array containing 5 random integers from 0 to 100:

In [34]:
from numpy import random
x=random.randint(100, size=(5))
print(x)

[92  2 19 55 34]


#### Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

In [35]:
from numpy import random
x = random.randint(100, size=(3, 5))
print(x)

[[51 55 56 14 17]
 [25 21 48 37 64]
 [99 83 62 82 95]]


#### Generate a 1-D array containing 5 random floats:

In [36]:
from numpy import random
x = random.rand(5)
print(x)

[0.02601316 0.37158279 0.83069732 0.94775097 0.10780494]


#### Generate a 2-D array with 3 rows, each row containing 5 random numbers:

In [37]:
from numpy import random
x = random.rand(3, 5)
print(x)

[[0.29713679 0.43541485 0.55178876 0.33950165 0.46352389]
 [0.56917855 0.69137925 0.36381683 0.2807111  0.70753622]
 [0.30244558 0.55544781 0.27999378 0.17411722 0.51161029]]


### Generate Random Number From Array
##### choice() method allows you to generate a random value based on an array of values.
##### The choice() method takes an array as a parameter and randomly returns one of the values.
#### Return one of the values in an array:

In [38]:
from numpy import random
x = random.choice([3, 5, 7, 9])
print(x)

5


#### Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

In [39]:
from numpy import random
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[3 7 3 9 5]
 [9 3 9 3 5]
 [7 7 7 9 9]]


In [11]:
import numpy as np
a=np.array([45,67,8,9,43])
print(a.sum())
print(a.mean())
print(a.max())
print(a.min())

172
34.4
67
8
